provider: pihole
policy: upsert-only
txtOwnerId: 'homelab'
pihole:
  server: http://pihole-web.pihole-system.svc.cluster.local
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_API_VERSION
    value: '6'
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password
serviceAccount:
  create: true
  name: 'external-dns'
ingressClassFilters:
  - nginx-internal
