ingress:
  enabled: true
  ingressClassName: nginx-internal
  host: longhorn.home
service:
  ui:
    type: LoadBalancer
    loadBalancerIP: 192.168.2.249
    annotations:
      metallb.universe.tf/allow-shared-ip: longhorn-svc
  manager:
    type: LoadBalancer
    loadBalancerIP: 192.168.2.249
    annotations:
      metallb.universe.tf/allow-shared-ip: longhorn-svc
