---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
spec:
  addresses:
    # Range of 192.168.2.192 - 192.168.2.255
    - 192.168.2.192/26
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool
