---
DNS1:
  192.168.2.1
persistentVolumeClaim:
  enabled: true
  storageClassName: longhorn
ingress:
  enabled: true
  ingressClassName: nginx-internal
  hosts:
    - 'pihole.home'
serviceWeb:
  loadBalancerIP: 192.168.2.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.2.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
